name: cv_project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - python=3.10.5=ha86cf86_0_cpython
  - zlib=1.2.13=h166bdaf_4
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cudnn=8.9.2.26=cuda11_0
  - filelock=3.20.0=py310h06a4308_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.6=py310h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libuv=1.48.0=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - markupsafe=3.0.2=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.3=h7f8727e_2
  - networkx=3.4.2=py310h06a4308_0
  - nodejs=20.17.0=hb8e3597_0
  - numpy=2.0.1=py310h5f9d8c6_1
  - numpy-base=2.0.1=py310hb5e798b_1
  - openssl=3.0.17=h5eee18b_0
  - pip=25.2=pyhc872135_1
  - pyyaml=6.0.2=py310h5eee18b_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.38.5=hc218d9a_0
  - sympy=1.14.0=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7b6447c_0
  - pytorch=2.5.1=py3.10_cpu_0
  - pytorch-mutex=1.0=cpu
  - torchaudio=2.5.1=py310_cpu
  - pip:
    - accelerate==0.24.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.0
    - aiohttp-proxy==0.1.2
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.7.1
    - async-timeout==5.0.1
    - attrs==25.4.0
    - audioread==3.1.0
    - av==16.0.1
    - beautifulsoup4==4.14.2
    - certifi==2022.12.7
    - cffi==2.0.0
    - charset-normalizer==2.1.1
    - click==8.3.0
    - colored==2.3.1
    - coloredlogs==15.0.1
    - compel==2.0.2
    - contourpy==1.3.2
    - controlnet_aux==0.0.7
    - ctranslate2==3.15.0
    - cuda-bindings==13.0.3
    - cuda-pathfinder==1.3.2
    - cuda-python==12.6.0
    - cycler==0.12.1
    - datasets==4.4.1
    - decorator==5.2.1
    - diffusers==0.24.0
    - dill==0.4.0
    - einops==0.8.1
    - exceptiongroup==1.3.0
    - fastapi==0.104.1
    - ffmpeg==1.4
    - ffmpeg-python==0.2.0
    - fire==0.7.1
    - flatbuffers==25.9.23
    - fonttools==4.60.1
    - frozenlist==1.8.0
    - fsspec==2025.9.0
    - future==1.0.0
    - gdown==5.2.0
    - gputil==1.4.0
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httptools==0.7.1
    - httpx==0.28.1
    - huggingface-hub==0.19.4
    - humanfriendly==10.0
    - idna==3.4
    - imageio==2.37.0
    - importlib_metadata==8.7.0
    - joblib==1.5.2
    - kagglehub==0.3.13
    - kiwisolver==1.4.9
    - lazy_loader==0.4
    - librosa==0.11.0
    - llvmlite==0.45.1
    - lpips==0.1.4
    - markdown2==2.5.4
    - matplotlib==3.10.7
    - more-itertools==10.8.0
    - msgpack==1.1.2
    - multidict==6.7.0
    - multiprocess==0.70.18
    - numba==0.62.1
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==9.10.2.21
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.1.105
    - omegaconf==2.3.0
    - onnx==1.15.0
    - onnx-graphsurgeon==0.3.26
    - onnxruntime==1.16.3
    - openai-whisper==20250625
    - opencv-python==4.10.0.84
    - packaging==25.0
    - pandas==2.3.3
    - peft==0.6.0
    - pillow==11.3.0
    - platformdirs==4.5.0
    - polars==1.35.2
    - polars-runtime-32==1.35.2
    - polygraphy==0.47.1
    - pooch==1.8.2
    - propcache==0.4.1
    - protobuf==3.20.2
    - psutil==7.1.0
    - pyarrow==22.0.0
    - pycparser==2.23
    - pydantic==2.12.2
    - pydantic_core==2.41.4
    - pydub==0.25.1
    - pyparsing==3.2.5
    - pysocks==1.7.1
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.1.1
    - python-multipart==0.0.20
    - pytz==2025.2
    - regex==2025.9.18
    - requests==2.32.5
    - safetensors==0.6.2
    - scikit-image==0.25.2
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - segment-anything==1.0
    - shellingham==1.5.4
    - six==1.17.0
    - sniffio==1.3.1
    - soundfile==0.13.1
    - soupsieve==2.8
    - soxr==1.0.0
    - stable-fast==0.0.15.post1+torch211cu121
    - starlette==0.27.0
    - streamdiffusion==0.1.1
    - tensorrt==9.0.1.post11.dev4
    - tensorrt-bindings==9.0.1.post11.dev4
    - tensorrt-libs==9.0.1.post11.dev4
    - termcolor==3.1.0
    - threadpoolctl==3.6.0
    - tifffile==2025.5.10
    - tiktoken==0.12.0
    - timm==1.0.20
    - tokenizers==0.15.2
    - torch==2.1.0
    - torchvision==0.16.0+cu121
    - tqdm==4.67.1
    - transformers==4.35.2
    - triton==2.1.0
    - typer-slim==0.20.0
    - typing-inspection==0.4.2
    - ultralytics==8.3.229
    - ultralytics-thop==2.0.18
    - urllib3==1.26.13
    - uvicorn==0.24.0.post1
    - uvloop==0.22.1
    - watchfiles==1.1.1
    - websockets==15.0.1
    - xformers==0.0.22.post7
    - xxhash==3.6.0
    - yarl==1.22.0
    - zipp==3.23.0
prefix: /home/infres/ziliu-24/anaconda3/envs/cv_project

